import Navbar from '../components/landing/Navbar';

export default function Terms() {
    return (
        <div className="min-h-screen bg-background text-foreground" style={{ fontFamily: '"Google Sans", Inter, sans-serif' }}>
            <Navbar />
            <main className="pt-24 pb-16 px-6">
                <div className="max-w-3xl mx-auto">
                    <p className="text-xs text-muted-foreground mb-2">Last updated: April 15, 2026</p>
                    <h1 className="text-3xl font-semibold mb-8">Terms and Conditions</h1>

                    <p className="text-muted-foreground mb-10">
                        Please read these Terms and Conditions carefully before using Zevian. By accessing or using our platform, you agree to be bound by these terms.
                    </p>

                    <div className="space-y-10">

                        <Section title="1. About Zevian">
                            <p>Zevian is an AI-powered performance management platform that helps managers of remote and distributed teams track, document, and evaluate employee performance through structured work reports and AI-assisted scoring.</p>
                            <p className="mt-3">Zevian is operated by Reza Hassan, a sole proprietor based in Bangladesh ("we", "us", "our"). Our platform is available at app.zevian.co.</p>
                        </Section>

                        <Section title="2. Definitions">
                            <ul className="list-disc pl-5 space-y-2">
                                <li><strong>"Platform"</strong> refers to the Zevian web application and all related services.</li>
                                <li><strong>"Customer"</strong> or <strong>"you"</strong> refers to the organization or individual that subscribes to the Platform.</li>
                                <li><strong>"Manager"</strong> refers to a user with administrative or managerial access within a Customer account.</li>
                                <li><strong>"Employee"</strong> refers to a team member added to the Platform by a Customer.</li>
                                <li><strong>"Subscription"</strong> refers to the paid access plan selected by the Customer.</li>
                                <li><strong>"AI Scores"</strong> refers to automated performance scores generated by our AI system based on employee-submitted reports.</li>
                            </ul>
                        </Section>

                        <Section title="3. Eligibility">
                            <p>You must be at least 18 years old and have the legal authority to enter into contracts on behalf of your organization. By using Zevian, you confirm that you meet these requirements.</p>
                        </Section>

                        <Section title="4. Account Registration">
                            <p>To use Zevian, you must create an account and invite team members. You are responsible for:</p>
                            <ul className="list-disc pl-5 mt-2 space-y-1">
                                <li>Providing accurate registration information</li>
                                <li>Maintaining the security of your account credentials</li>
                                <li>All activity that occurs under your account</li>
                                <li>Ensuring that employees added to your account have been informed of and have consented to their performance data being processed on the Platform</li>
                            </ul>
                            <p className="mt-3">You must notify us immediately at <a href="mailto:hello@zevian.co" className="text-foreground underline underline-offset-4">hello@zevian.co</a> if you suspect unauthorized access to your account.</p>
                        </Section>

                        <Section title="5. Subscriptions and Billing">
                            <SubSection title="5.1 Pricing">
                                <p>Zevian is offered as a subscription-based service. Pricing is based on the number of active users (seats) in your account and is displayed at checkout.</p>
                            </SubSection>
                            <SubSection title="5.2 Billing cycle">
                                <p>Subscriptions are billed on a monthly basis. Your billing date is set when you first subscribe.</p>
                            </SubSection>
                            <SubSection title="5.3 Payment">
                                <p>Payments are processed by our third-party payment processor, Lemon Squeezy. By subscribing, you agree to Lemon Squeezy's terms of service and authorize recurring charges.</p>
                            </SubSection>
                            <SubSection title="5.4 Automatic renewal">
                                <p>Subscriptions renew automatically at the end of each billing cycle. You may cancel at any time before your renewal date to avoid being charged for the next period.</p>
                            </SubSection>
                            <SubSection title="5.5 Refunds">
                                <p>Payments are non-refundable except where required by applicable law. If you believe a charge was made in error, contact us at <a href="mailto:hello@zevian.co" className="text-foreground underline underline-offset-4">hello@zevian.co</a> within 7 days.</p>
                            </SubSection>
                        </Section>

                        <Section title="6. Acceptable Use">
                            <p>You agree not to use the Platform to:</p>
                            <ul className="list-disc pl-5 mt-2 space-y-1">
                                <li>Violate any applicable law or regulation</li>
                                <li>Infringe the intellectual property rights of any third party</li>
                                <li>Transmit malicious code, viruses, or harmful software</li>
                                <li>Attempt to gain unauthorized access to any part of the Platform or its infrastructure</li>
                                <li>Use the Platform to harass, discriminate against, or harm any individual</li>
                                <li>Reverse engineer, decompile, or copy any part of the Platform</li>
                            </ul>
                        </Section>

                        <Section title="7. AI-Generated Scores and Content">
                            <SubSection title="7.1 Informational purpose">
                                <p>AI Scores generated by the Platform are intended as a data-driven reference point to support manager judgment. They are not a substitute for professional human assessment and should not be the sole basis for employment decisions, including but not limited to promotions, terminations, or disciplinary actions.</p>
                            </SubSection>
                            <SubSection title="7.2 No guarantee of accuracy">
                                <p>AI Scores are generated based on the content of employee-submitted reports and the criteria configured by the Manager. Zevian does not guarantee that AI Scores will be accurate, complete, or free from error.</p>
                            </SubSection>
                            <SubSection title="7.3 Customer responsibility">
                                <p>The Customer is solely responsible for how AI Scores are interpreted and used within their organization. Any employment decisions remain the full responsibility of the Customer and their designated Managers.</p>
                            </SubSection>
                            <SubSection title="7.4 Third-party AI provider">
                                <p>AI scoring is powered by Google's Gemini API. By using the Platform, you acknowledge that report content may be transmitted to Google's API for processing in accordance with Google's data use policies.</p>
                            </SubSection>
                        </Section>

                        <Section title="8. Data Ownership">
                            <p>You retain full ownership of all data submitted to the Platform, including employee reports, performance scores, and organizational settings. We do not claim any rights over your data.</p>
                            <p className="mt-3">You grant Zevian a limited license to store, process, and display your data solely for the purpose of providing the Platform's services.</p>
                        </Section>

                        <Section title="9. Confidentiality">
                            <p>We treat all Customer data as confidential. We will not share, sell, or disclose your data to third parties except as required to operate the Platform (see Privacy Policy) or as required by applicable law.</p>
                        </Section>

                        <Section title="10. Availability and Maintenance">
                            <p>We aim to keep the Platform available at all times but do not guarantee uninterrupted access. We may perform scheduled maintenance with reasonable notice where possible. We are not liable for downtime resulting from circumstances outside our reasonable control.</p>
                        </Section>

                        <Section title="11. Intellectual Property">
                            <p>All software, design, trademarks, and content comprising the Platform are the intellectual property of Zevian or its licensors. Nothing in these Terms grants you any ownership of Platform IP. You may not copy, reproduce, or create derivative works from any part of the Platform without our written consent.</p>
                        </Section>

                        <Section title="12. Limitation of Liability">
                            <p>To the maximum extent permitted by applicable law:</p>
                            <ul className="list-disc pl-5 mt-2 space-y-2">
                                <li>Zevian's total liability to you for any claim arising from your use of the Platform shall not exceed the amount you paid to Zevian in the 3 months preceding the claim.</li>
                                <li>Zevian shall not be liable for any indirect, incidental, consequential, or special damages, including loss of profits, loss of data, or business interruption, even if advised of the possibility of such damages.</li>
                                <li>Zevian is not liable for any employment decisions made by a Customer based on AI Scores or any other data generated by the Platform.</li>
                            </ul>
                        </Section>

                        <Section title="13. Indemnification">
                            <p>You agree to indemnify and hold Zevian harmless from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the Platform, your violation of these Terms, or any employment decision you make in connection with data generated by the Platform.</p>
                        </Section>

                        <Section title="14. Termination">
                            <SubSection title="14.1 By you">
                                <p>You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing cycle. Your data will be retained for 30 days following cancellation, after which it may be permanently deleted.</p>
                            </SubSection>
                            <SubSection title="14.2 By us">
                                <p>We may suspend or terminate your account if you violate these Terms, or if required by law. We will provide reasonable notice where possible.</p>
                            </SubSection>
                        </Section>

                        <Section title="15. Changes to These Terms">
                            <p>We may update these Terms from time to time. When we do, we will update the "Last updated" date at the top of this page. If changes are material, we will notify you by email at least 7 days before they take effect. Your continued use of the Platform after changes take effect constitutes your acceptance.</p>
                        </Section>

                        <Section title="16. Governing Law">
                            <p>These Terms are governed by the laws of Bangladesh. Any disputes arising from these Terms or your use of the Platform shall first be attempted to be resolved through good-faith negotiation. If unresolved, disputes shall be submitted to the courts of Bangladesh, unless otherwise required by applicable consumer protection law in your jurisdiction.</p>
                        </Section>

                        <Section title="17. Contact">
                            <p>For any questions about these Terms, contact us at:</p>
                            <div className="mt-3 space-y-1">
                                <p><strong>Email:</strong> <a href="mailto:hello@zevian.co" className="text-foreground underline underline-offset-4">hello@zevian.co</a></p>
                                <p><strong>Website:</strong> zevian.co</p>
                            </div>
                        </Section>

                    </div>
                </div>
            </main>
            <footer className="py-12 text-center border-t border-border/50">
                <p className="text-xs text-muted-foreground">© 2026 Zevian. All rights reserved.</p>
            </footer>
        </div>
    );
}

function Section({ title, children }) {
    return (
        <section>
            <h2 className="text-lg font-semibold mb-3">{title}</h2>
            <div className="text-muted-foreground space-y-2 text-sm leading-relaxed">
                {children}
            </div>
            <div className="mt-8 h-px bg-gradient-to-r from-transparent via-border to-transparent" />
        </section>
    );
}

function SubSection({ title, children }) {
    return (
        <div className="mt-4">
            <h3 className="text-sm font-medium text-foreground mb-2">{title}</h3>
            {children}
        </div>
    );
}
